version: "3.7"

services:
  dagster:
    image: tomlewis20/victor_test:latest
    ports:
      - 3000:3000
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
