name: dagster
channels:
  - defaults
dependencies:
  - abseil-cpp=20230802.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - grpc-cpp=1.48.2
  - gtest=1.14.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libprotobuf=3.20.3
  - ncurses=6.4
  - openssl=3.0.11
  - pip=23.3
  - python=3.11.5
  - re2=2022.04.01
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - alembic==1.12.1
      - aniso8601==9.0.1
      - annotated-types==0.6.0
      - anyio==4.0.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - azure-common==1.1.28
      - azure-core==1.29.5
      - azure-identity==1.12.0
      - azure-keyvault-secrets==4.7.0
      - azure-mgmt-core==1.4.0
      - azure-mgmt-eventgrid==10.2.0
      - azure-mgmt-storage==21.0.0
      - azure-storage-blob==12.18.3
      - azure-storage-file-datalake==12.12.0
      - backoff==2.2.1
      - bitarray==2.8.2
      - boto3==1.28.2
      - botocore==1.31.76
      - certifi==2023.7.22
      - cffi==1.16.0
      - cftime==1.6.3
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmake==3.27.7
      - coloredlogs==14.0
      - croniter==2.0.1
      - cryptography==41.0.5
      - cytoolz==0.12.2
      - dagster==1.5.5
      - dagster-graphql==1.5.5
      - dagster-pipes==1.5.5
      - dagster-pyspark==0.21.5
      - dagster-spark==0.21.5
      - dagster-webserver==1.5.5
      - databricks-sdk==0.9.0
      - databricks-sql-connector==2.9.3
      - dataclasses-json==0.5.14
      - delta-sharing==1.0.0
      - delta-spark==2.4.0
      - deltalake==0.12.0
      - dependency-injector==4.41.0
      - docstring-parser==0.15
      - ecmwf-api-client==1.6.3
      - et-xmlfile==1.1.0
      - eth-abi==4.2.1
      - eth-account==0.10.0
      - eth-hash==0.5.2
      - eth-keyfile==0.6.1
      - eth-keys==0.4.0
      - eth-rlp==0.3.0
      - eth-typing==3.5.1
      - eth-utils==2.3.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - googleapis-common-protos==1.61.0
      - gql==3.4.1
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - grpcio==1.59.2
      - grpcio-health-checking==1.59.2
      - grpcio-status==1.59.2
      - h11==0.14.0
      - hexbytes==0.3.1
      - httptools==0.6.1
      - humanfriendly==10.0
      - hvac==1.1.1
      - idna==3.4
      - importlib-metadata==6.8.0
      - isodate==0.6.1
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - langchain==0.0.291
      - langsmith==0.0.56
      - lightgbm==4.1.0
      - lru-dict==1.2.0
      - lz4==4.3.2
      - mako==1.2.4
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - msal==1.24.1
      - msal-extensions==1.0.0
      - msrest==0.7.1
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - netcdf4==1.6.4
      - numexpr==2.8.7
      - numpy==1.26.1
      - oauthlib==3.2.2
      - openai==0.27.8
      - openpyxl==3.1.2
      - packaging==23.2
      - pandas==2.1.2
      - parsimonious==0.9.0
      - pendulum==2.1.2
      - pillow==10.1.0
      - polars==0.18.8
      - portalocker==2.8.2
      - protobuf==4.25.0
      - py4j==0.10.9.7
      - pyarrow==12.0.0
      - pycparser==2.21
      - pycryptodome==3.19.0
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pyhcl==0.4.5
      - pyjwt==2.8.0
      - pyspark==3.4.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - pytz==2023.3.post1
      - pytzdata==2020.1
      - pyyaml==6.0.1
      - referencing==0.30.2
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==0.10.1
      - rlp==3.0.0
      - rpds-py==0.10.6
      - rtdip-sdk==0.8.7
      - s3transfer==0.6.2
      - scipy==1.11.3
      - semver==3.0.0
      - sniffio==1.3.0
      - sqlalchemy==1.4.50
      - starlette==0.31.1
      - tabulate==0.9.0
      - tenacity==8.2.3
      - thrift==0.16.0
      - tomli==2.0.1
      - toolz==0.12.0
      - toposort==1.10
      - tqdm==4.66.1
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - universal-pathlib==0.1.4
      - urllib3==1.26.18
      - uvicorn==0.23.2
      - uvloop==0.19.0
      - watchdog==3.0.0
      - watchfiles==0.21.0
      - web3==6.5.0
      - websockets==12.0
      - xarray==2023.7.0
      - xlrd==2.0.1
      - yarl==1.9.2
      - zipp==3.17.0